### ISSUE TITLE
Unread messages in muted channels show a notification

### ISSUE THREAD

**Issue by adlk** [meetfranz/recipe-slack#1]
Original ticket by: @jvdmeij

---

### Expected Behavior
I would expect a muted channel to not trigger a notification.

### Current Behavior
The red notification icon is being shown.

### Steps to Reproduce (for bugs)
Add Slack as a channel
Mute a channel
Ask someone to post something in that channel
Notification badge is shown in the service bar

### Your Environment
* Franz Version used: Version 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: Mac OSX 10.13

**Comment by jvdmeij** [comment]
Thanks for copy/pasting!

**Comment by jvdmeij** [comment]
The guys at Rambox also had some issues with this. A proposed solution can be found at https://github.com/saenzramiro/rambox/issues/1169 - if you guys have the same method of checking for unread messages.
