### ISSUE TITLE
Sign-in with Google doesn't work anymore

### ISSUE THREAD

**Issue by stanleynguyen** [meetfranz/recipe-slack#16]

**Comment by DalderupMaurice** [comment]
Can't this just be implemented in the client itself? 
https://github.com/getferdi/ferdi/pull/1991/files

**Comment by DalderupMaurice** [comment]
shouldn't be closed tho, it is not implemented yet in Franz

**Comment by stanleynguyen** [comment]
> shouldn't be closed tho, it is not implemented yet in Franz

You can actually do it from the Slack service already. I was getting the workspace id incorrect previously
