### ISSUE TITLE
Slack shortcut(s) are not working

### ISSUE THREAD

**Issue by LazyTarget** [meetfranz/recipe-slack#6]
I always use the shortcut Ctrl + T for navigating around in Slack.
It easily finds and jumps trough people, channels, private channels.

For me it is kind of a deal breaker. I will continue using the Slack client until this is fixed. But it would be wonderful to have it in the same place as everything else :)

Tried with 5.0.0 and beta 5.0.1-beta.1 on Windows 10

Great product!! 🥇

**Comment by jonohill** [comment]
This is because Franz is effectively a browser... and Ctrl-T is usually for tabs.
If you can retrain your brain try using Ctrl-K instead - this works everywhere Slack does and it maps to the same thing

**Comment by LazyTarget** [comment]
Great suggestion, I listened to your advice and have retrained my brain 👌 
Closing issue...
