### ISSUE TITLE
Please update your third-party app or use the Slack desktop app

### ISSUE THREAD

**Issue by daniellukaszgmailcom** [meetfranz/recipe-slack#7]
I use Linux and Franz 5.0.0-beta.15. I have the warning from the attachment on the Slack service tab. Unfortunately Slack is no longer usable. 
![Zaznaczenie_001](https://user-images.githubusercontent.com/29166713/54767301-28831880-4bfd-11e9-9b31-f172a3c12d70.png)
Thanks for your product and support! ;)

**Comment by HenkeJohansson** [comment]
Same issue for me running Ubuntu 18.04 and Franz 5.0.0-beta.13

**Comment by daniellukaszgmailcom** [comment]
this works for me: https://github.com/meetfranz/franz/issues/1347
